### ISSUE TITLE
Installation Instructions

### ISSUE THREAD

**Issue by wonderwareguru** [RapidScada/scada-community#2]
Hi, I'm new with RapidScada... Can someone please provide installation instructions for this MQTT plugin.

Thank you.

**Comment by 2mik** [comment]
Hi,
Instructions are [here](https://github.com/RapidScada/scada-community/tree/master/Drivers/KpMqtt). Please translate it from Russian by Google. We're going to add a translation in the future.

**Comment by 2mik** [comment]
General installation instructions available at http://doc.rapidscada.net/content/latest/en/installation-and-run/module-installation.html
