### ISSUE TITLE
GrafanaDataProvider Not supported 6.1.1?

### ISSUE THREAD

**Issue by ruoshui9527** [RapidScada/scada-community#24]
Deploy GrafanaDataProvider service in windows environment, web.config file configure scadaweb environment, web if is 5.8.4, grafana show normal. 6.1.1 can't get data under 6.1.1. Is it because of the change of dat file name between the two versions?

Is it necessary to modify this part of the code to be able to do it? But I don't find this part in github?

![图片](https://user-images.githubusercontent.com/104556597/235109005-7179df9b-ae29-45ed-a8de-fe6fc3ae761c.png)

**Comment by 2mik** [comment]
We faced that Grafana plugins, such as grafana-simple-json-datasource, become obsolete too often and unpredictable.
We decided not too use special plugins to integrate Rapid SCADA and Grafana. With Rapid SCADA 6.x you should configure archives to store historical data into database, then display data by Grafana. I suggest storing historical data to PostgreSQL.

**Comment by ruoshui9527** [comment]
ok,thanks

**Comment by greenfoxx** [comment]
Could you please check short instructions for working with Grafana 
PostgreSQL data source and Rapid SCADA
1. Choose as data source PostgreSQL.
2. Set the data source’s basic configuration options in setting tab.
For example:
Host: The IP address/hostname your PostgreSQL instance
Database: rapid_scada
User: postgres
Password: Database user’s postgres password -  postgres
3. Write a sql-query. You can use Query builder or Query editor.
4. Simple query example (Query on one channel, not including into stat = 0, and also not showing a gap, if there is no data in a certain period of time)

_SELECT
  time_stamp AS "time",
  val
FROM mod_arc_postgre_sql.mincopy_historical
WHERE
  cnl_num = 101
ORDER BY 1_
