### ISSUE TITLE
JSON formatted payload support

### ISSUE THREAD

**Issue by kumajaya** [RapidScada/scada-community#7]
Any plant to add JSON formatted payload as I asked [here](https://github.com/bersim/OpenKPs/issues/10#issuecomment-532255466)? Or just like my own [dirty solution](https://github.com/kumajaya/scada-community/commit/a8a7bce35deb4c3f1e0ae604be3685b47d2e1027)  for ThingsBoard.

**Comment by 2mik** [comment]
I suppose we should add this.

**Comment by 2mik** [comment]
Included in the release v5.3.1

**Comment by kumajaya** [comment]
Thank you.
